const state={overview:null,selectedTaskId:null,selectedTab:'overview'};
const repoMeta=document.getElementById('repoMeta');
const summaryStats=document.getElementById('summaryStats');
const taskList=document.getElementById('taskList');
const currentPanel=document.getElementById('currentPanel');
const detailBody=document.getElementById('detailBody');
const eventList=document.getElementById('eventList');
const tabs=[...document.querySelectorAll('.tab')];
tabs.forEach((tab)=>tab.addEventListener('click',()=>{state.selectedTab=tab.dataset.tab;tabs.forEach((item)=>item.classList.toggle('active',item===tab));renderDetail();}));
function escapeHtml(value){return String(value??'').replace(/[&<>\"]/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
function renderOverview(){const overview=state.overview;if(!overview)return;repoMeta.textContent=overview.repoRoot+' · developer: '+overview.developer+' · updated: '+overview.updatedAt;summaryStats.innerHTML='';const pills=[['active',overview.summary.activeCount],['archived',overview.summary.archivedCount],['agent',overview.currentAgent||'none']];Object.entries(overview.summary.byStatus||{}).forEach(([key,value])=>pills.push([key,value]));for(const [label,value] of pills){const span=document.createElement('div');span.className='stat-pill';span.textContent=label+': '+value;summaryStats.appendChild(span);}const allTasks=[...overview.tasks,...overview.archivedTasks];if(!state.selectedTaskId&&allTasks.length){state.selectedTaskId=(overview.currentTask&&overview.currentTask.id)||allTasks[0].id;}taskList.innerHTML='';for(const task of allTasks){const card=document.createElement('div');card.className='task-card'+(task.id===state.selectedTaskId?' active':'');card.innerHTML='<div><strong>'+escapeHtml(task.title)+'</strong></div><div class="task-meta">'+escapeHtml(task.id)+' · <span class="badge '+escapeHtml(task.status)+'">'+escapeHtml(task.status)+'</span></div><div class="task-meta">'+escapeHtml(task.assignee||'unassigned')+' · '+task.researchFileCount+' research · '+task.implementContextCount+'/'+task.checkContextCount+' ctx</div>';card.addEventListener('click',()=>{state.selectedTaskId=task.id;renderOverview();renderDetail();});taskList.appendChild(card);}const current=overview.currentTask;currentPanel.innerHTML=current?'<div class="kv"><div>Current task</div><div><strong>'+escapeHtml(current.title)+'</strong></div><div>Status</div><div><span class="badge '+escapeHtml(current.status)+'">'+escapeHtml(current.status)+'</span></div><div>Current agent</div><div>'+escapeHtml(overview.currentAgent||'unknown')+'</div><div>Artifacts</div><div>'+current.artifactProgress+'/'+current.artifactTotal+' core artifacts, '+current.researchFileCount+' research files</div><div>Session pointers</div><div>'+overview.sessions.length+'</div></div>':'<div class="muted">No active Trellis task.</div>';eventList.innerHTML='';for(const event of overview.events.slice(0,50)){const div=document.createElement('div');div.className='event-card';div.innerHTML='<div><strong>'+escapeHtml(event.event||'event')+'</strong></div><div class="task-meta">'+escapeHtml(event.platform||'unknown')+' · '+escapeHtml(event.agent||event.tool||'')+'</div><div class="task-meta">'+escapeHtml(event.ts||'')+'</div>';eventList.appendChild(div);}}
async function renderDetail(){if(!state.selectedTaskId){detailBody.innerHTML='<div class="muted">Select a task.</div>';return;}const res=await fetch('/api/tasks/'+encodeURIComponent(state.selectedTaskId));if(!res.ok){detailBody.textContent='Task detail not available';return;}const data=await res.json();const {summary,detail}=data;if(state.selectedTab==='overview'){detailBody.innerHTML='<div class="kv"><div>ID</div><div>'+escapeHtml(summary.id)+'</div><div>Title</div><div>'+escapeHtml(summary.title)+'</div><div>Status</div><div><span class="badge '+escapeHtml(summary.status)+'">'+escapeHtml(summary.status)+'</span></div><div>Assignee</div><div>'+escapeHtml(summary.assignee||'')+'</div><div>Package</div><div>'+escapeHtml(summary.package||'')+'</div><div>Task dir</div><div class="code">'+escapeHtml(summary.taskDir)+'</div></div>';return;}if(state.selectedTab==='prd'){detailBody.innerHTML='<div class="code">'+escapeHtml(detail.prd||'(missing)')+'</div>';return;}if(state.selectedTab==='info'){detailBody.innerHTML='<div class="code">'+escapeHtml(detail.info||'(missing)')+'</div>';return;}if(state.selectedTab==='context'){detailBody.innerHTML='<div class="code">'+escapeHtml(JSON.stringify({implement:detail.implementContext,check:detail.checkContext},null,2))+'</div>';return;}if(state.selectedTab==='research'){detailBody.innerHTML='<div class="code">'+escapeHtml(JSON.stringify(detail.research,null,2))+'</div>';return;}if(state.selectedTab==='summary'){detailBody.innerHTML='<div class="code">'+escapeHtml(detail.summary||'(missing)')+'</div>';return;}detailBody.innerHTML='<div class="code">'+escapeHtml(JSON.stringify(detail.task,null,2))+'</div>';}
async function refresh(){const res=await fetch('/api/overview');state.overview=await res.json();renderOverview();await renderDetail();}
const stream=new EventSource('/api/stream');
stream.addEventListener('update',(event)=>{const payload=JSON.parse(event.data);state.overview=payload.state;renderOverview();renderDetail();});
refresh();
